version: 0.0
os: linux
files:
  - source: /
    destination: /opt/www/personal
hooks:
  BeforeInstall:
    - location: Scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: Scripts/build.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: Scripts/start_services.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: Scripts/stop_services.sh
      timeout: 300
      runas: root