import { solveEulerProblem1 } from './1-10/EulerProblem1';
import { solveEulerProblem2 } from './1-10/EulerProblem2';
import { solveEulerProblem3 } from './1-10/EulerProblem3';
import { solveEulerProblem4 } from './1-10/EulerProblem4';
import { solveEulerProblem5 } from './1-10/EulerProblem5';
import { solveEulerProblem6 } from './1-10/EulerProblem6';
import { solveEulerProblem7 } from './1-10/EulerProblem7';
import { solveEulerProblem8 } from './1-10/EulerProblem8';
import { solveEulerProblem9 } from './1-10/EulerProblem9';
import { solveEulerProblem10 } from './1-10/EulerProblem10';
import { EulerProblem } from './EulerProblem';

export const EulerProblemList: EulerProblem[] = [
	{
		id: 1,
		title: 'Multiples of 3 or 5',
		text: `If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
Find the sum of all the multiples of 3 or 5 below 1000.`,
		getAnswer: solveEulerProblem1
	},
	{
		id: 2,
		title: 'Even Fibonacci Numbers',
		text: `Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.`,
		getAnswer: solveEulerProblem2
	},
	{
		id: 3,
		title: 'Largest Prime Factor',
		text: `The prime factors of 13195 are 5, 7, 13 and 29.
What is the largest prime factor of the number 600851475143 ?`,
		getAnswer: solveEulerProblem3
	},
	{
		id: 4,
		title: 'Largest Palindrome Product',
		text: `A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.
Find the largest palindrome made from the product of two 3-digit numbers.`,
		getAnswer: solveEulerProblem4
	},
	{
		id: 5,
		title: 'Smallest Multiple',
		text: `2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?`,
		getAnswer: solveEulerProblem5
	},
	{
		id: 6,
		title: 'Sum Square Difference',
		text: `The sum of the squares of the first ten natural numbers is, 1^2 + 2^2 + 3^2 ... + 10^2 = 385
The square of the sum of the first ten natural numbers is, (1 + 2 + 3... + 10)^2 = 3025
Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 - 385 = 2640.
Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.`,
		getAnswer: solveEulerProblem6
	},
	{
		id: 7,
		title: '10001st Prime',
		text: `By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.
What is the 10 001st prime number?`,
		getAnswer: solveEulerProblem7
	},
	{
		id: 8,
		title: 'Largest Product in a Series',
		text: `The four adjacent digits in the 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832.
Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product? (1000 digit number removed for sanity)`,
		getAnswer: solveEulerProblem8
	},
	{
		id: 9,
		title: 'Special Pythagorean Triplet',
		text: `A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,
a^2 + b^2 = c^2
For example, 32 + 42 = 9 + 16 = 25 = 52.
There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.`,
		getAnswer: solveEulerProblem9
	},
	{
		id: 10,
		title: 'Summation of primes',
		text: `The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.
Find the sum of all the primes below two million.`,
		getAnswer: solveEulerProblem10
	}
].reverse();